### PR TITLE
correct path on Windows

### PR DESCRIPTION
**Pull request by chorny**

### CODE REVIEW

**Comment by chorny** [comment]
Yes, I tried this way first. But it strips ':' where it must remain. So "c:\tempdir\d:\perlfiles\module.pm" is converted to "c\tempdir\d\perlfiles\module.pm". That's why in call to__safe_dir_and_file from  __shadow_filename, ':' must be stripped, but in call from __make_path_file it must not.

**Comment by jhi** [comment]
On Thursday-201601-14 8:19, Alexandr Ciornii wrote:
> Yes, I tried this way first. But it strips ':' where it must remain. So
> "c:\tempdir\d:\perlfiles\module.pm" is converted to
> "c\tempdir\d\perlfiles\module.pm". That's why in call
> to__safe_dir_and_file from __shadow_filename, ':' must be stripped, but
> in call from __make_path_file it must not.

Ah.  Let me think a bit the most natural way of shaping the API.  I am
a little uncertain that the explicit stripcolon is what I want.

**Comment by jhi** [comment]
I bravely pushed release v0.007.

**Comment by jhi** [comment]
I think the latest releases of PPI-Xref already deal with this issue.

**Pull request closed without merging**
